name: Build Plugin
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: jamescodesthings/smapi:latest
          options: -v ${{ github.workspace }}:/plugin -e PASSWORD=${{ secrets.IMAGE_PASSWORD }}
          run: |
            cd /plugin
            ./set-version.sh "${{ steps.vars.outputs.tag }}"
            ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./*.zip
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          artifacts: "*.zip"
